version: "3.8"

services:
  risc-db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5431:5432"
    volumes:
      - data:/var/lib/postgresql/data
  risc-app:
    container_name: risc-app-dev
    image: risc-app-img-dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    depends_on:
      - risc-db
    volumes:
      - ../:/app
    ports:
      - 4004:8080

volumes:
  data: